theme: jekyll-theme-cayman
title: Data Science Portfolio
baseurl: /Portfolio
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - course.md
  - /course_content/module_1.md
  - /course_content/module_2.md
  - /course_content/module_3.md
